/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MonitorRouteImport } from './routes/monitor'
import { Route as ApiAgentmailRouteImport } from './routes/api/agentmail'
import { Route as ApiCanvasRouteImport } from './routes/api/canvas'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiEmbeddableRouteImport } from './routes/api/embeddable'
import { Route as ApiPlansRouteImport } from './routes/api/plans'
import { Route as ApiResearchRouteImport } from './routes/api/research'
import { Route as ApiSettingsRouteImport } from './routes/api/settings'
import { Route as ApiVoiceRouteImport } from './routes/api/voice'
import { Route as PSlugRouteImport } from './routes/p.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorRoute = MonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentmailRoute = ApiAgentmailRouteImport.update({
  id: '/api/agentmail',
  path: '/api/agentmail',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCanvasRoute = ApiCanvasRouteImport.update({
  id: '/api/canvas',
  path: '/api/canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmbeddableRoute = ApiEmbeddableRouteImport.update({
  id: '/api/embeddable',
  path: '/api/embeddable',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlansRoute = ApiPlansRouteImport.update({
  id: '/api/plans',
  path: '/api/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResearchRoute = ApiResearchRouteImport.update({
  id: '/api/research',
  path: '/api/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsRoute = ApiSettingsRouteImport.update({
  id: '/api/settings',
  path: '/api/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceRoute = ApiVoiceRouteImport.update({
  id: '/api/voice',
  path: '/api/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/monitor': typeof MonitorRoute
  '/api/agentmail': typeof ApiAgentmailRoute
  '/api/canvas': typeof ApiCanvasRoute
  '/api/chat': typeof ApiChatRoute
  '/api/embeddable': typeof ApiEmbeddableRoute
  '/api/plans': typeof ApiPlansRoute
  '/api/research': typeof ApiResearchRoute
  '/api/settings': typeof ApiSettingsRoute
  '/api/voice': typeof ApiVoiceRoute
  '/p/$slug': typeof PSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/monitor': typeof MonitorRoute
  '/api/agentmail': typeof ApiAgentmailRoute
  '/api/canvas': typeof ApiCanvasRoute
  '/api/chat': typeof ApiChatRoute
  '/api/embeddable': typeof ApiEmbeddableRoute
  '/api/plans': typeof ApiPlansRoute
  '/api/research': typeof ApiResearchRoute
  '/api/settings': typeof ApiSettingsRoute
  '/api/voice': typeof ApiVoiceRoute
  '/p/$slug': typeof PSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/monitor': typeof MonitorRoute
  '/api/agentmail': typeof ApiAgentmailRoute
  '/api/canvas': typeof ApiCanvasRoute
  '/api/chat': typeof ApiChatRoute
  '/api/embeddable': typeof ApiEmbeddableRoute
  '/api/plans': typeof ApiPlansRoute
  '/api/research': typeof ApiResearchRoute
  '/api/settings': typeof ApiSettingsRoute
  '/api/voice': typeof ApiVoiceRoute
  '/p/$slug': typeof PSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/monitor'
    | '/api/agentmail'
    | '/api/canvas'
    | '/api/chat'
    | '/api/embeddable'
    | '/api/plans'
    | '/api/research'
    | '/api/settings'
    | '/api/voice'
    | '/p/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/monitor'
    | '/api/agentmail'
    | '/api/canvas'
    | '/api/chat'
    | '/api/embeddable'
    | '/api/plans'
    | '/api/research'
    | '/api/settings'
    | '/api/voice'
    | '/p/$slug'
  id:
    | '__root__'
    | '/'
    | '/monitor'
    | '/api/agentmail'
    | '/api/canvas'
    | '/api/chat'
    | '/api/embeddable'
    | '/api/plans'
    | '/api/research'
    | '/api/settings'
    | '/api/voice'
    | '/p/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MonitorRoute: typeof MonitorRoute
  ApiAgentmailRoute: typeof ApiAgentmailRoute
  ApiCanvasRoute: typeof ApiCanvasRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiEmbeddableRoute: typeof ApiEmbeddableRoute
  ApiPlansRoute: typeof ApiPlansRoute
  ApiResearchRoute: typeof ApiResearchRoute
  ApiSettingsRoute: typeof ApiSettingsRoute
  ApiVoiceRoute: typeof ApiVoiceRoute
  PSlugRoute: typeof PSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor': {
      id: '/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof MonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agentmail': {
      id: '/api/agentmail'
      path: '/api/agentmail'
      fullPath: '/api/agentmail'
      preLoaderRoute: typeof ApiAgentmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/canvas': {
      id: '/api/canvas'
      path: '/api/canvas'
      fullPath: '/api/canvas'
      preLoaderRoute: typeof ApiCanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/embeddable': {
      id: '/api/embeddable'
      path: '/api/embeddable'
      fullPath: '/api/embeddable'
      preLoaderRoute: typeof ApiEmbeddableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plans': {
      id: '/api/plans'
      path: '/api/plans'
      fullPath: '/api/plans'
      preLoaderRoute: typeof ApiPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/research': {
      id: '/api/research'
      path: '/api/research'
      fullPath: '/api/research'
      preLoaderRoute: typeof ApiResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings': {
      id: '/api/settings'
      path: '/api/settings'
      fullPath: '/api/settings'
      preLoaderRoute: typeof ApiSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice': {
      id: '/api/voice'
      path: '/api/voice'
      fullPath: '/api/voice'
      preLoaderRoute: typeof ApiVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MonitorRoute: MonitorRoute,
  ApiAgentmailRoute: ApiAgentmailRoute,
  ApiCanvasRoute: ApiCanvasRoute,
  ApiChatRoute: ApiChatRoute,
  ApiEmbeddableRoute: ApiEmbeddableRoute,
  ApiPlansRoute: ApiPlansRoute,
  ApiResearchRoute: ApiResearchRoute,
  ApiSettingsRoute: ApiSettingsRoute,
  ApiVoiceRoute: ApiVoiceRoute,
  PSlugRoute: PSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
