/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCanvasRouteImport } from './routes/api/canvas'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiEmbeddableRouteImport } from './routes/api/embeddable'
import { Route as ApiResearchRouteImport } from './routes/api/research'
import { Route as ApiVoiceRouteImport } from './routes/api/voice'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCanvasRoute = ApiCanvasRouteImport.update({
  id: '/api/canvas',
  path: '/api/canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmbeddableRoute = ApiEmbeddableRouteImport.update({
  id: '/api/embeddable',
  path: '/api/embeddable',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResearchRoute = ApiResearchRouteImport.update({
  id: '/api/research',
  path: '/api/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceRoute = ApiVoiceRouteImport.update({
  id: '/api/voice',
  path: '/api/voice',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/canvas': typeof ApiCanvasRoute
  '/api/chat': typeof ApiChatRoute
  '/api/embeddable': typeof ApiEmbeddableRoute
  '/api/research': typeof ApiResearchRoute
  '/api/voice': typeof ApiVoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/canvas': typeof ApiCanvasRoute
  '/api/chat': typeof ApiChatRoute
  '/api/embeddable': typeof ApiEmbeddableRoute
  '/api/research': typeof ApiResearchRoute
  '/api/voice': typeof ApiVoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/canvas': typeof ApiCanvasRoute
  '/api/chat': typeof ApiChatRoute
  '/api/embeddable': typeof ApiEmbeddableRoute
  '/api/research': typeof ApiResearchRoute
  '/api/voice': typeof ApiVoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/canvas'
    | '/api/chat'
    | '/api/embeddable'
    | '/api/research'
    | '/api/voice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/canvas'
    | '/api/chat'
    | '/api/embeddable'
    | '/api/research'
    | '/api/voice'
  id:
    | '__root__'
    | '/'
    | '/api/canvas'
    | '/api/chat'
    | '/api/embeddable'
    | '/api/research'
    | '/api/voice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCanvasRoute: typeof ApiCanvasRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiEmbeddableRoute: typeof ApiEmbeddableRoute
  ApiResearchRoute: typeof ApiResearchRoute
  ApiVoiceRoute: typeof ApiVoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/canvas': {
      id: '/api/canvas'
      path: '/api/canvas'
      fullPath: '/api/canvas'
      preLoaderRoute: typeof ApiCanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/embeddable': {
      id: '/api/embeddable'
      path: '/api/embeddable'
      fullPath: '/api/embeddable'
      preLoaderRoute: typeof ApiEmbeddableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/research': {
      id: '/api/research'
      path: '/api/research'
      fullPath: '/api/research'
      preLoaderRoute: typeof ApiResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice': {
      id: '/api/voice'
      path: '/api/voice'
      fullPath: '/api/voice'
      preLoaderRoute: typeof ApiVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCanvasRoute: ApiCanvasRoute,
  ApiChatRoute: ApiChatRoute,
  ApiEmbeddableRoute: ApiEmbeddableRoute,
  ApiResearchRoute: ApiResearchRoute,
  ApiVoiceRoute: ApiVoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
